# backend/render.yaml
services:
  - type: web
    name: kaparthi-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: YOUTUBE_API_KEY
        value: your_api_key_here
      - key: CHANNEL_ID
        value: your_channel_id_here
      - key: SHORTS_PLAYLIST_ID
        value: your_playlist_id_here
